# Generated by Django 5.2.4 on 2025-08-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_role_subscriptionplan_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_upload_articles',
            field=models.BooleanField(default=False),
        ),
    ]
