# Generated by Django 5.2.4 on 2025-08-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_newsarticle_author_newsarticle_heading_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='article_upload_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
