# Generated by Django 5.2.4 on 2025-08-10 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rolechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='accounts.category'),
        ),
    ]
