# Generated by Django 5.2.4 on 2025-08-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_newsarticle_status_alter_newsarticle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
